(cl:defpackage yahboomcar_msgs-srv
  (:use )
  (:export
   "ROBOTARMARRAY"
   "<ROBOTARMARRAY-REQUEST>"
   "ROBOTARMARRAY-REQUEST"
   "<ROBOTARMARRAY-RESPONSE>"
   "ROBOTARMARRAY-RESPONSE"
   "KINEMARICS"
   "<KINEMARICS-REQUEST>"
   "KINEMARICS-REQUEST"
   "<KINEMARICS-RESPONSE>"
   "KINEMARICS-RESPONSE"
  ))

