// Generated by gencpp from file yahboomcar_msgs/RobotArmArray.msg
// DO NOT EDIT!


#ifndef YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAY_H
#define YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAY_H

#include <ros/service_traits.h>


#include <yahboomcar_msgs/RobotArmArrayRequest.h>
#include <yahboomcar_msgs/RobotArmArrayResponse.h>


namespace yahboomcar_msgs
{

struct RobotArmArray
{

typedef RobotArmArrayRequest Request;
typedef RobotArmArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotArmArray
} // namespace yahboomcar_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yahboomcar_msgs::RobotArmArray > {
  static const char* value()
  {
    return "22eb2a15e67062ad54355cfa936a9cdb";
  }

  static const char* value(const ::yahboomcar_msgs::RobotArmArray&) { return value(); }
};

template<>
struct DataType< ::yahboomcar_msgs::RobotArmArray > {
  static const char* value()
  {
    return "yahboomcar_msgs/RobotArmArray";
  }

  static const char* value(const ::yahboomcar_msgs::RobotArmArray&) { return value(); }
};


// service_traits::MD5Sum< ::yahboomcar_msgs::RobotArmArrayRequest> should match
// service_traits::MD5Sum< ::yahboomcar_msgs::RobotArmArray >
template<>
struct MD5Sum< ::yahboomcar_msgs::RobotArmArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yahboomcar_msgs::RobotArmArray >::value();
  }
  static const char* value(const ::yahboomcar_msgs::RobotArmArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yahboomcar_msgs::RobotArmArrayRequest> should match
// service_traits::DataType< ::yahboomcar_msgs::RobotArmArray >
template<>
struct DataType< ::yahboomcar_msgs::RobotArmArrayRequest>
{
  static const char* value()
  {
    return DataType< ::yahboomcar_msgs::RobotArmArray >::value();
  }
  static const char* value(const ::yahboomcar_msgs::RobotArmArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yahboomcar_msgs::RobotArmArrayResponse> should match
// service_traits::MD5Sum< ::yahboomcar_msgs::RobotArmArray >
template<>
struct MD5Sum< ::yahboomcar_msgs::RobotArmArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yahboomcar_msgs::RobotArmArray >::value();
  }
  static const char* value(const ::yahboomcar_msgs::RobotArmArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yahboomcar_msgs::RobotArmArrayResponse> should match
// service_traits::DataType< ::yahboomcar_msgs::RobotArmArray >
template<>
struct DataType< ::yahboomcar_msgs::RobotArmArrayResponse>
{
  static const char* value()
  {
    return DataType< ::yahboomcar_msgs::RobotArmArray >::value();
  }
  static const char* value(const ::yahboomcar_msgs::RobotArmArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAY_H
