// Generated by gencpp from file yahboomcar_msgs/RobotArmArrayRequest.msg
// DO NOT EDIT!


#ifndef YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAYREQUEST_H
#define YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yahboomcar_msgs
{
template <class ContainerAllocator>
struct RobotArmArrayRequest_
{
  typedef RobotArmArrayRequest_<ContainerAllocator> Type;

  RobotArmArrayRequest_()
    : apply()  {
    }
  RobotArmArrayRequest_(const ContainerAllocator& _alloc)
    : apply(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _apply_type;
  _apply_type apply;





  typedef boost::shared_ptr< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotArmArrayRequest_

typedef ::yahboomcar_msgs::RobotArmArrayRequest_<std::allocator<void> > RobotArmArrayRequest;

typedef boost::shared_ptr< ::yahboomcar_msgs::RobotArmArrayRequest > RobotArmArrayRequestPtr;
typedef boost::shared_ptr< ::yahboomcar_msgs::RobotArmArrayRequest const> RobotArmArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator1> & lhs, const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.apply == rhs.apply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator1> & lhs, const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yahboomcar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8e8b3a3b74f38e6cd4cf9904695ae0f";
  }

  static const char* value(const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8e8b3a3b74f38e6ULL;
  static const uint64_t static_value2 = 0xcd4cf9904695ae0fULL;
};

template<class ContainerAllocator>
struct DataType< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yahboomcar_msgs/RobotArmArrayRequest";
  }

  static const char* value(const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string apply\n"
;
  }

  static const char* value(const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.apply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotArmArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yahboomcar_msgs::RobotArmArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "apply: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.apply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YAHBOOMCAR_MSGS_MESSAGE_ROBOTARMARRAYREQUEST_H
